/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TAMY;

import Conectar.Conectar;
import Formulario.Reloj;
import java.awt.Color;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author TAMY-IA
 */
public class TAMY extends javax.swing.JFrame {
    
    //VARIABLES GLOBALES
    public static String a;
    //////////////////////

    /**
     * Creates new form TAMY
     */
    public TAMY() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);//PARA CAMBIAR EL COLOR DEL FONDO DEL JTEXTAREA
        this.setLocationRelativeTo(null);
        jtaTAMY.setLineWrap(true);//PARA QUE LAS CADENAS NO SE PASEN DEL CAMPO VISIBLE EN EL JTAXTAREA
        
        ///////////////////
        Reloj rj=new Reloj(jlHora);
        rj.start();
        
        jlFecha.setText(fecha());
        ///////////////////
        

        
    }
    
    void Ejecutar(){
        String comando=txtDato.getText();
        jtaTAMY.append("-> "+comando+" "+"- "+jlHora.getText()+"\n");
        txtDato.setText("");
        //TAMY();
    }
    
    void TAMY(){
        String Hora=jlHora.getText();
        jtaTAMY.append("->1 "+" - "+Hora+"\n");
        //txtDato.setText(Hora);
        /*
        if(){
            
        }
        */
        jtaTAMY.setText("Bienvenido mi nombre es TAMY \n");
        
        /////////////////AQUI INICIAN LAS PREGUNTAS/////////////////////////////////
        
        /////////////////AQUI TERMINAN LAS PREGUNTAS/////////////////////////////////
    }
    
    public static String fecha(){
        java.util.Date fecha = new java.util.Date();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
        
        return formatofecha.format(fecha);
    }
    
    void fecha2(){
        Date objDate = new Date(); // Sistema actual La fecha y la hora se asignan a objDate 
 
        System.out.println(objDate); 
        String strDateFormat = "hh: mm: ss a dd-MMM-aaaa"; // El formato de fecha está especificado  
        SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat); // La cadena de formato de fecha se pasa como un argumento al objeto 
        //de formato de fecha  
        System.out.println(objSDF.format(objDate)); // El formato de fecha se aplica a la fecha actual
    }
    //////////Protocolos de seguridad//////////////////////////////////////////
    public static String id;
    
    void ProtocoloNivelAcceso(){
        
    }
    
    ///////////Fin de protocoloes de seguridad///////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlHora = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlTAMY = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaTAMY = new javax.swing.JTextArea();
        txtDato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TAMY Soporte");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlHora.setForeground(new java.awt.Color(0, 204, 0));
        jlHora.setText("HH:MM:SS");
        jPanel2.add(jlHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 60, 20));

        jlFecha.setForeground(new java.awt.Color(0, 204, 0));
        jlFecha.setText("DD/MM/AAAA");
        jPanel2.add(jlFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 80, 20));

        jlTAMY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMY/Interfaz_1.gif"))); // NOI18N
        jPanel2.add(jlTAMY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 286));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jtaTAMY.setEditable(false);
        jtaTAMY.setBackground(new java.awt.Color(0, 0, 0));
        jtaTAMY.setColumns(20);
        jtaTAMY.setForeground(new java.awt.Color(0, 204, 0));
        jtaTAMY.setRows(5);
        jScrollPane1.setViewportView(jtaTAMY);

        txtDato.setBackground(new java.awt.Color(0, 0, 0));
        txtDato.setForeground(new java.awt.Color(0, 204, 0));
        txtDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDato)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDato, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 349, 330, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Tecnologias Cobra");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoActionPerformed
        // TODO add your handling code here:
        Ejecutar();
    }//GEN-LAST:event_txtDatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TAMY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TAMY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlTAMY;
    private javax.swing.JTextArea jtaTAMY;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
