/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Conectar.Conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;

/**
 *
 * @author TAMY
 */
public class Correo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Correo
     */
    public Correo() {
        initComponents();
        this.setLocation(440, 100);
    }
    
    public void Correo(String dato){
        Conectar cc=new Conectar();
        Connection cn=cc.conexion();
        
        try{
            String lista="SELECT * FROM `buzon` WHERE `id`='"+dato+"'";
            String [] Correos= new String[1];
            //Vector vector=new Vector();
            
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(lista);
            
            while(rs.next()==true){
                //contactos[0]=rs.getString(2)+"\n "+rs.getString(3)+" "+rs.getString(5)+" "+rs.getString(6);     //si se quiere obneter nombres completos de usuarios
                //Correos[0]="<html>"+rs.getString(2)+" --- "+rs.getString(5)+"<br>"+rs.getString(3)+" "+rs.getString(6)+"<html>";
                jtCorreo.append("NOMBRE: \n"+rs.getString(2)+"\n\n"+"ASUNTO: \n"+rs.getString(3)+"\n\n"+"MENSAJE: \n"+rs.getString(4)+"\n\n\n FECHA DE ENVIO: \n"+rs.getString(5));
                //vector.addElement(Correos[0]);
                //jtCorreo.setListData(vector);
            }
            
            cc.CerrarConexion();
            
        }catch(Exception ex){
            System.out.println("Error al cargar leidos\n"+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCorreo = new javax.swing.JTextArea();
        btnReponder = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setTitle("Correos Electronicos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        jtCorreo.setEditable(false);
        jtCorreo.setColumns(20);
        jtCorreo.setLineWrap(true);
        jtCorreo.setRows(5);
        jScrollPane1.setViewportView(jtCorreo);

        btnReponder.setText("Responder");
        btnReponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReponderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReponder)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReponder)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReponderActionPerformed
        // TODO add your handling code here:
        EnviarCorreo ec=new EnviarCorreo();
        Principal.jdpEscritorio.add(ec);
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReponderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReponder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtCorreo;
    // End of variables declaration//GEN-END:variables
}
