/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Conectar.Conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TAMY-IA
 */
public class Pendientes extends javax.swing.JInternalFrame {
    DefaultTableModel model;
    /**
     * Creates new form Pendientes
     */
    public Pendientes() {
        initComponents();
        this.setLocation(440, 10);
    }
    
    public void CargarTareas(String valor){
        try{
            String[] titulos={"ID","Nombre","Categoria","Estado", "Fecha"};
            String[] registros=new String[5];
            model=new DefaultTableModel(null, titulos);
            String cons="SELECT `folio`,`nombre`,`categoria`,`estado`,`fecha` FROM tareas WHERE `estado`='"+valor+"'";
            
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(cons);
            
            while(rs.next()){
                registros[0]=rs.getString(1);
                registros[1]=rs.getString(2);
                registros[2]=rs.getString(3);
                registros[3]=rs.getString(4);
                registros[4]=rs.getString(5);
                
                model.addRow(registros);
                
            }
            
            tbElementos.setModel(model);
            
        }catch(Exception e){
            System.out.println("Error al cargar la lista elementos pendientes\n"+e);
        }
    }   //TAREAS    PENDIENTE
       
    public void CargarInvitaciones(String valor){
        try{
            String[] titulos={"ID","Nombre","Estado"};
            String[] registros=new String[3];
            model=new DefaultTableModel(null, titulos);
            String cons="SELECT `folio`,`nombre`,`invitacion` FROM asistencia_invitado WHERE `invitacion`='"+valor+"'";
            
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(cons);
            
            while(rs.next()){
                registros[0]=rs.getString(1);
                registros[1]=rs.getString(2);
                registros[2]=rs.getString(3);
                
                model.addRow(registros);
                
            }
            
            tbElementos.setModel(model);
            
        }catch(Exception e){
            System.out.println("Error al cargar la lista elementos invitaciones\n"+e);
        }
    } //TERMINADO
    
    public void CargarPresupuestos(String valor){
        try{
            String[] titulos={"Folio","Nombre","Cantidad","Estado","Expiracion"};
            String[] registros=new String[5];
            model=new DefaultTableModel(null, titulos);
            String cons="SELECT `folio`, `nombre`, `cantidad`, `estado`, `expiracion` FROM pagos WHERE estado='"+valor+"'";
            
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(cons);
            
            while(rs.next()){
                registros[0]=rs.getString(1);
                registros[1]=rs.getString(2);
                registros[2]=rs.getString(3);
                registros[3]=rs.getString(4);
                registros[4]=rs.getString(5);
                
                model.addRow(registros);
                
            }
            
            tbElementos.setModel(model);
            
        }catch(Exception e){
            System.out.println("Error al cargar la lista elementos presupuesto\n"+e);
        }
    }
    
    public void CargarPagosProveedores(String valor){
        try{
            String[] titulos={"Folio","Nombre","Cantidad","Estado","Expiracion"};
            String[] registros=new String[5];
            model=new DefaultTableModel(null, titulos);
            String cons="SELECT `folio`, `nombre`, `cantidad`, `estado`, `expiracion` FROM pagos WHERE estado='"+valor+"'";
            
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(cons);
            
            while(rs.next()){
                registros[0]=rs.getString(1);
                registros[1]=rs.getString(2);
                registros[2]=rs.getString(3);
                registros[3]=rs.getString(4);
                registros[4]=rs.getString(5);
                
                model.addRow(registros);
                
            }
            
            tbElementos.setModel(model);
            
        }catch(Exception e){
            System.out.println("Error al cargar la lista elementos presupuesto\n"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbElementos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Tablero");

        tbElementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null},
                {null, null, "", null},
                {null, null, "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Estado", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tbElementos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbElementos;
    // End of variables declaration//GEN-END:variables
    Conectar cc=new Conectar();
    Connection cn=cc.conexion();
}
