/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Conectar.Conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author TAMY
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        Reloj hilo = new Reloj(jlHora);
        hilo.start();
        Folio();
        jlFolio.setVisible(false);
    }
       
    void Folio(){
        int j;
        int cont=1;
        String num="";
        String c="";
         String SQL="SELECT MAX(folio) FROM eventos";
       
        try {
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            if(rs.next()){              
                 c=rs.getString(1);
            }
            
            if(c==null){
                jlFolio.setText("00000001");
                jmFolio.setText("Evento: "+"00000001");
            }
            else{
                 j=Integer.parseInt(c);
                 GenerarNumero gen= new GenerarNumero();
                 gen.generar(j);
                 jlFolio.setText(gen.serie());
                 jmFolio.setText("Evento: "+gen.serie());
            }
            //cn.close();
        } catch (SQLException ex) {
            System.out.println("Error en el folio principal \n"+ex);
           Logger.getLogger(Presupuesto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Seguridad(String usuario){
        String tipo="";
         String nivel="SELECT * FROM usuario WHERE `usuario`='"+usuario+"'";
         //System.out.println("funciona");
         try{
            Statement st =cn.createStatement();
            ResultSet rs=st.executeQuery(nivel);
            
            while(rs.next()){
                //id=rs.getString(1);
                //nom=rs.getString(2);
                tipo=rs.getString(3);
                //nacimiento=rs.getString(4);
                //usuario=rs.getString(5);
                //pass=rs.getString(6);
            }//FIN WHILE
         }catch(Exception e){
            System.out.println("Error al al validar el tipo de usuario\n"+e);
         }
         
         if(tipo.equals("Administrador")){
             //System.out.println("admin");
             DesbloquearAdmin();
             this.setVisible(true);
         }else if(tipo.equals("Cliente")){
             //System.out.println("cliente");
             DesbloquearCliente();
             this.setVisible(true);
         }
         
    }
    
    void DesbloquearAdmin(){
        
    }
    
    void DesbloquearCliente(){
        System.out.println("Cliente");
        jmNuevo.setEnabled(false);
        jmRegistrar.setEnabled(false);
        btnPresupuesto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdpEscritorio = new javax.swing.JDesktopPane();
        btnListaTarea = new javax.swing.JButton();
        btnInvitados = new javax.swing.JButton();
        btnPresupuesto = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jlHora = new javax.swing.JLabel();
        jlFolio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmNuevo = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jmRegEventos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmRegistrar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmFolio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alpes_Eventos");

        jdpEscritorio.setBackground(new java.awt.Color(25, 153, 153));

        btnListaTarea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnListaTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/order-192_1.png"))); // NOI18N
        btnListaTarea.setText("<html>Lista De<br>Tareas<html>");
        btnListaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaTareaActionPerformed(evt);
            }
        });
        jdpEscritorio.add(btnListaTarea);
        btnListaTarea.setBounds(30, 110, 190, 70);

        btnInvitados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInvitados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contact-new.png"))); // NOI18N
        btnInvitados.setText("Invitados");
        btnInvitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitadosActionPerformed(evt);
            }
        });
        jdpEscritorio.add(btnInvitados);
        btnInvitados.setBounds(240, 110, 190, 70);

        btnPresupuesto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mini_faq-lector-pinpad.png"))); // NOI18N
        btnPresupuesto.setText("Presupuesto");
        btnPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresupuestoActionPerformed(evt);
            }
        });
        jdpEscritorio.add(btnPresupuesto);
        btnPresupuesto.setBounds(30, 200, 190, 70);

        btnProveedores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mini_employee.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        jdpEscritorio.add(btnProveedores);
        btnProveedores.setBounds(240, 200, 190, 70);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sql.png"))); // NOI18N
        jButton5.setText("Tablero");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jdpEscritorio.add(jButton5);
        jButton5.setBounds(30, 290, 400, 80);

        jlHora.setFont(new java.awt.Font("Tahoma", 1, 85)); // NOI18N
        jlHora.setForeground(new java.awt.Color(255, 255, 255));
        jlHora.setText("00:00:00");
        jdpEscritorio.add(jlHora);
        jlHora.setBounds(40, 30, 386, 70);

        jlFolio.setText("Folio2");
        jdpEscritorio.add(jlFolio);
        jlFolio.setBounds(190, 10, 110, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        jmArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo_2.png"))); // NOI18N
        jmArchivo.setText("Archivo");

        jmNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modif.png"))); // NOI18N
        jmNuevo.setText("Nuevo Usuario");
        jmNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevoActionPerformed(evt);
            }
        });
        jmArchivo.add(jmNuevo);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout (2)_1.png"))); // NOI18N
        jMenuItem11.setText("Cerrar Sesion");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jmArchivo.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_ 32x32px (2).png"))); // NOI18N
        jMenuItem12.setText("Salir");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jmArchivo.add(jMenuItem12);

        jMenuBar1.add(jmArchivo);

        jmRegEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informe_1.png"))); // NOI18N
        jmRegEventos.setText("Gestionar Evento");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagos.png"))); // NOI18N
        jMenuItem2.setText("Calendario De Eventos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmRegEventos.add(jMenuItem2);

        jmRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/order-192_1.png"))); // NOI18N
        jmRegistrar.setText("Registro De Eventos");
        jmRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarActionPerformed(evt);
            }
        });
        jmRegEventos.add(jmRegistrar);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajadores.png"))); // NOI18N
        jMenuItem4.setText("Asistencia");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmRegEventos.add(jMenuItem4);

        jMenuBar1.add(jmRegEventos);

        jmFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mini_58274.png"))); // NOI18N
        jmFolio.setText("Folio");
        jmFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFolioActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmFolio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevoActionPerformed
        // TODO add your handling code here:
        LoginRegistro lr=new LoginRegistro();
        jdpEscritorio.add(lr);
        lr.setVisible(true);
    }//GEN-LAST:event_jmNuevoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        CalendarioEventos ce=new CalendarioEventos();
        jdpEscritorio.add(ce);
        ce.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarActionPerformed
        // TODO add your handling code here:
        RegistroEventos re=new RegistroEventos();
        jdpEscritorio.add(re);
        re.setVisible(true);
    }//GEN-LAST:event_jmRegistrarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        RegistroInvitados ri=new RegistroInvitados();
        jdpEscritorio.add(ri);
        ri.setVisible(true);
        //Thread th=new Thread(new RegistroInvitados());
        //th.start();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnListaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaTareaActionPerformed
        // TODO add your handling code here:
        ListaTarea lt=new ListaTarea();
        jdpEscritorio.add(lt);
        lt.setVisible(true);
        //Thread cargar=new Thread(new ListaTarea());
        //cargar.start();
    }//GEN-LAST:event_btnListaTareaActionPerformed

    private void btnInvitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitadosActionPerformed
        // TODO add your handling code here:
        RegistrarInvitados ri=new RegistrarInvitados();
        jdpEscritorio.add(ri);
        ri.setVisible(true);
    }//GEN-LAST:event_btnInvitadosActionPerformed

    private void btnPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresupuestoActionPerformed
        // TODO add your handling code here:
        ListaPresupuesto lp=new ListaPresupuesto();
        jdpEscritorio.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_btnPresupuestoActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        ListaProveedores lps=new ListaProveedores();
        jdpEscritorio.add(lps);
        lps.setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TablaPendientes tp=new TablaPendientes();
        jdpEscritorio.add(tp);
        tp.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jmFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFolioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "funciona");
    }//GEN-LAST:event_jmFolioActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        this.dispose();
        Login lg=new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {/*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvitados;
    private javax.swing.JButton btnListaTarea;
    private javax.swing.JButton btnPresupuesto;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JDesktopPane jdpEscritorio;
    public static javax.swing.JLabel jlFolio;
    private javax.swing.JLabel jlHora;
    private javax.swing.JMenu jmArchivo;
    public static javax.swing.JMenu jmFolio;
    private javax.swing.JMenuItem jmNuevo;
    private javax.swing.JMenu jmRegEventos;
    private javax.swing.JMenuItem jmRegistrar;
    // End of variables declaration//GEN-END:variables
    Conectar cc=new Conectar();
    Connection cn=cc.conexion();
}
