/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Conectar.Conectar;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TAMY-IA
 */
public class RegistroInvitados extends javax.swing.JInternalFrame implements Runnable{

    DefaultTableModel model;
    /**
     * Creates new form RegistroInvitados
     */
    public RegistroInvitados() {
        initComponents();
        this.setLocation(440, 50);
        CargarLista("");
    }
    
    public void run(){
        int i=0;
        while(true){
            CargarLista("");
            i++;
            System.out.println("hilo--->"+i);
            try{
                sleep(1000);
            }catch(Exception ex){
                
            }
        }
    }
    
    void CargarLista(String valor){
        try{
            String[] titulos={"ID","Nombre","Relacion","Mesa","Asistencia"};
            String[] registros=new String[5];
            model=new DefaultTableModel(null, titulos);
            
            String consulta="SELECT * FROM `asistencia_invitado` WHERE CONCAT (`idAsistencia_Invitado`,'', `nombre`,'', `relacion`,'', `mesa`,'', `asistencia`) LIKE '%"+valor+"%'";
            
            Statement st = cn.createStatement(); 
            ResultSet rs=st.executeQuery(consulta);
            
            while(rs.next()){
                registros[0]=rs.getString(1);
                registros[1]=rs.getString(3);
                registros[2]=rs.getString(8);
                registros[3]=rs.getString(9);
                registros[4]=rs.getString(13);
                
                model.addRow(registros);
            }
            
            tbInvitados.setModel(model);
            tbInvitados.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbInvitados.getColumnModel().getColumn(1).setPreferredWidth(225);
            tbInvitados.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbInvitados.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbInvitados.getColumnModel().getColumn(4).setPreferredWidth(10);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la lista\n"+ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInvitados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAsistencia = new javax.swing.JButton();

        setClosable(true);
        setTitle("Asistencia");

        tbInvitados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbInvitados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Buscar:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Lista de invitados");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        btnAsistencia.setText("Asistencia");
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsistencia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsistencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        // TODO add your handling code here:
        String asistir="✓";
        int filase1=tbInvitados.getSelectedRow();
       
        try{
            if(filase1==-1){
                JOptionPane.showMessageDialog(null, "Por favor seleccione un invitado");
               
            }else{
                String codigo=(String)tbInvitados.getValueAt(filase1, 0);
                //String con="UPDATE `Asistencia_Invitado` SET `asistencia` = '✓' WHERE `idAsistencia_Invitado` ='"+codigo+"'";
                String sql="UPDATE asistencia_invitado SET `asistencia`='"+asistir+"' WHERE `idAsistencia_Invitado`='"+codigo+"'";
                System.out.println("Funciona3>>>>> "+codigo+" "+asistir);
                try{
                    PreparedStatement pst = cn.prepareStatement(sql);
                    pst.executeUpdate();
                    //JOptionPane.showMessageDialog(null, "Actualizado");
                   System.out.println("Funciona3>>>>> "+sql);
                   CargarLista("");
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Error al realizar el pago\n"+ex);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error al asistir\n"+ex);
        }
        
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        CargarLista(txtNombre.getText());
    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int fila = tbInvitados.getSelectedRow();
	
        try {

            String id="",nombre="",relacion="",mesa="";

           if(fila==-1){
               JOptionPane.showMessageDialog(null, "No ha seleccionado ningun presupuesto");
           }else{
               
               RegistrarInvitados ri=new RegistrarInvitados();
               Principal.jdpEscritorio.add(ri);
               ri.setVisible(true);
         
               id=(String)tbInvitados.getValueAt(fila, 0).toString();
               nombre =  (String)tbInvitados.getValueAt(fila, 1).toString();
               relacion =  (String)tbInvitados.getValueAt(fila, 2).toString();
               mesa =  (String)tbInvitados.getValueAt(fila, 3).toString();
               //estimada =  (String)tbInvitados.getValueAt(fila, 4).toString();

               RegistrarInvitados.jlTitulo.setText("Actualizar Invitado");
               RegistrarInvitados.jlId.setText(id);
               RegistrarInvitados.txtNombre.setText(nombre);
               RegistrarInvitados.txtRelacion.setText(relacion);
               RegistrarInvitados.txtMesa.setText(mesa);
               ri.CargarDatos(id);
               /*
               RegistrarInvitados.txtNota.setText(nota);
               RegistrarInvitados.txtCantidad.setText(estimada);
               RegistrarInvitados.jlEquilibrar.setText(estimada);
               */
            
            this.dispose();

           }
       }catch (Exception e) {
           System.out.println("Error aol enviar datos\n"+e);
       }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filase1= tbInvitados.getSelectedRow();
        int confirmar=JOptionPane.showConfirmDialog(null, "¿Eliminar Invitado?", "Confirmar Eliminacion", JOptionPane.YES_NO_OPTION);
        
        if(confirmar==JOptionPane.YES_OPTION){
            try{
            if(filase1==-1){
                JOptionPane.showMessageDialog(null, "Seleccione el invitado a eliminar");
            }else{
                String cod=(String)tbInvitados.getValueAt(filase1, 0);
                String eliminarSQL="DELETE FROM asistencia_invitado WHERE `idAsistencia_Invitado`='"+cod+"'";
                try{
                    PreparedStatement pst = cn.prepareStatement(eliminarSQL);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Eliminado");
                    CargarLista("");
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }catch(Exception e){
            
        }
        }else{
            //JOptionPane.showMessageDialog(null, "cancelado");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbInvitados;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    Conectar cc=new Conectar();
    Connection cn=cc.conexion();
}
